// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'data/db/model/bolus_quick_delivery_preset.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(1, 2608740991493324972),
    name: 'BolusQuickDeliveryPreset',
    lastPropertyId: const obx_int.IdUid(3, 5199921914061954045),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 390584428835294428),
        name: 'no',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 6845341626540871572),
        name: 'name',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 5199921914061954045),
        name: 'doseU',
        type: 8,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(
    getObjectBoxModel(),
    directory: directory ?? (await defaultStoreDirectory()).path,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    entities: _entities,
    lastEntityId: const obx_int.IdUid(1, 2608740991493324972),
    lastIndexId: const obx_int.IdUid(0, 0),
    lastRelationId: const obx_int.IdUid(0, 0),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [],
    retiredIndexUids: const [],
    retiredPropertyUids: const [],
    retiredRelationUids: const [],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    BolusQuickDeliveryPreset:
        obx_int.EntityDefinition<BolusQuickDeliveryPreset>(
          model: _entities[0],
          toOneRelations: (BolusQuickDeliveryPreset object) => [],
          toManyRelations: (BolusQuickDeliveryPreset object) => {},
          getId: (BolusQuickDeliveryPreset object) => object.no,
          setId: (BolusQuickDeliveryPreset object, int id) {
            object.no = id;
          },
          objectToFB: (BolusQuickDeliveryPreset object, fb.Builder fbb) {
            final nameOffset = fbb.writeString(object.name);
            fbb.startTable(4);
            fbb.addInt64(0, object.no);
            fbb.addOffset(1, nameOffset);
            fbb.addFloat64(2, object.doseU);
            fbb.finish(fbb.endTable());
            return object.no;
          },
          objectFromFB: (obx.Store store, ByteData fbData) {
            final buffer = fb.BufferContext(fbData);
            final rootOffset = buffer.derefObject(0);
            final noParam = const fb.Int64Reader().vTableGet(
              buffer,
              rootOffset,
              4,
              0,
            );
            final nameParam = const fb.StringReader(
              asciiOptimization: true,
            ).vTableGet(buffer, rootOffset, 6, '');
            final doseUParam = const fb.Float64Reader().vTableGet(
              buffer,
              rootOffset,
              8,
              0,
            );
            final object = BolusQuickDeliveryPreset(
              no: noParam,
              name: nameParam,
              doseU: doseUParam,
            );

            return object;
          },
        ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [BolusQuickDeliveryPreset] entity fields to define ObjectBox queries.
class BolusQuickDeliveryPreset_ {
  /// See [BolusQuickDeliveryPreset.no].
  static final no = obx.QueryIntegerProperty<BolusQuickDeliveryPreset>(
    _entities[0].properties[0],
  );

  /// See [BolusQuickDeliveryPreset.name].
  static final name = obx.QueryStringProperty<BolusQuickDeliveryPreset>(
    _entities[0].properties[1],
  );

  /// See [BolusQuickDeliveryPreset.doseU].
  static final doseU = obx.QueryDoubleProperty<BolusQuickDeliveryPreset>(
    _entities[0].properties[2],
  );
}
